apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hero
  name: hero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hero
  template:
    metadata:
      labels:
        app: hero
    spec:
      containers:
      - image: hero
        imagePullPolicy: Never
        name: hero
        ports:
        - containerPort: 8080